#!/bin/sh

# Copyright: 2016 François Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"


if ! which mongo >/dev/null 2>&1
then
    echo "Sorry, no mongo command found."
    exit 1
fi

mongo_code='m = rs.status().members; for(var i = 0; i < m.length; i++) { print(m[i]["health"]); }'

# This command below assume that a .mongorc.js file already
# exists and trigger automatically a connection as admin.
if output=$(timeout --kill-after=5s 10s printf '%s' "$mongo_code" | mongo --quiet | sort | uniq 2>&1)
then
  printf '%s' "$output"
  exit 0
else
  echo "The mongodb check has failed."
  exit 1
fi


