#!/bin/sh

# Copyright: 2014 Francois Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

codename=$(lsb_release --codename --short)

if [ "$codename" = "lenny" ] || [ "$codename" = "squeeze" ]
then
    echo "Sorry ipmi-sensors is not available in Lenny and Squeeze."
    exit 1
fi

if ! which ipmi-sensors >/dev/null 2>&1
then
    echo "No ipmi-sensors command. The package freeipmi-tools is probably not installed."
    exit 1
fi

# Load kernel modules.
if ! modprobe ipmi_devintf >/dev/null 2>&1
then
    echo "Sorry, impossible to load the kernel module ipmi_devintf."
    exit 1
fi

if ! modprobe ipmi_si >/dev/null 2>&1
then
    echo "Sorry, impossible to load the kernel module ipmi_si."
    exit 1
fi

output=$(timeout 6s ipmi-sensors                   \
            --quiet-cache --sdr-cache-recreate     \
            --quiet-readings --output-sensor-state \
            --ignore-not-available-sensors         \
            --ignore-unrecognized-events           \
            --interpret-oem-data                   \
            --comma-separated-output); exit_code="$?"

if [ "$exit_code" = "124" ]
then
    # "timeout" command has broken the "ipmi-sensors" execution.
    echo "Sorry, ipmi-sensors execution is too long."
else
    # The goal of cut is to limit the size of the output
    # (because with snmp the size is limited).
    # Field 2 => Name
    # Field 4 => State
    printf "%s\n" "$output" | sed -nr '1p;/(power|temp|chassis)/Ip' | cut -d',' -f'2,4'
fi

exit "$exit_code"


