#!/bin/sh

# Copyright: 2016 Francois Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}
. "$SCRIPT_DIRECTORY/share.sh"


cfg_file='/etc/haproxy/haproxy.cfg'

if [ ! -f "$cfg_file" ]
then
    end "$CODE_UNKNOWN" "Problem, no file %s found.\n" "$cfg_file"
fi


#######################
### The socket file ###
#######################

socket_file=$(grep -E '[[:space:]]*stats socket' "$cfg_file" | awk '{ print $3 }')

if [ -z "$socket_file" ]
then
    end "$CODE_UNKNOWN" \
    "Problem, no \"stats socket\" instruction found in the haproxy configuration.\n"
fi

if [ ! -e "$socket_file"  ]
then
    end "$CODE_UNKNOWN" \
    "Problem, the socket file %s (in the haproxy configuration) doesn't exist.\n" \
    "$socket_file"
fi

if [ ! -S "$socket_file"  ]
then
    end "$CODE_UNKNOWN" \
    "Problem, the file %s (in the haproxy configuration) isn't a socket.\n" \
    "$socket_file"
fi


####################
### The backends ###
####################

backends=$(grep -E '^[[:space:]]*backend[[:space:]]' "$cfg_file" | awk '{ print $2 }' | sort | uniq)

if [ -z "$backends" ]
then
    end "$CODE_UNKNOWN" \
    "Problem, no backend found in the haproxy configuration.\n"
fi

backends_regex=$(printf '%s' "$backends" | tr '\n' '|')
backends_regex='^('"${backends_regex%|}"')'


#################
### The stats ###
#################

if ! which nc.openbsd >/dev/null
then
    end "$CODE_UNKNOWN" \
    "Problem, the nc.openbsd command is not installed (you should install the package netcat-openbsd).\n"
fi

stats=$(echo "show stat" | nc -U "$socket_file" | grep -E "$backends_regex" | grep -v ',no check,')

if [ -z "$stats" ]
then
    end "$CODE_UNKNOWN" \
    "Problem, no stats found concerning the backends.\n"
fi

no_up=$(printf '%s' "$stats" | grep -v ',UP,' | cut -d',' -f'1,2' | head -n3 | tr '\n' ' ')

if [ -n "$no_up" ]
then
    end "$CODE_CRITICAL" \
    'HAproxy CRITICAL, some backends are not UP: %s(non-exhaustive list).\n' "$no_up"
else
    end "$CODE_OK" \
    'HAproxy OK, all backends are UP.\n'
fi


