#!/bin/sh

# Copyright: 2015 Francois Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# The goal of tail is to remove the head of the ps command.
#
# The command below is fine... but outputs too the "kernel"
# processes so that the output can too long, for instance longer than the
# MTU of the network. In this case, snmpget fails to retrieve the
# extend:
#
#    ps -e -o state,comm --sort comm | \
#        tail -n +2 | sort | uniq -c | sed -r 's/^[[:space:]]+//'
#
# So, to avoid this problem, we limit the output of the ps commande
# to the "non-kernel" processes via the "--ppid 2 --pid 2 --deselect"
# options. Trick found here:
#
#    http://unix.stackexchange.com/questions/78583/can-ps-display-only-non-kernel-processes-on-linux
#
#
ps --ppid 2 --pid 2 --deselect -o state,comm --sort comm | \
    tail -n +2 | sort | uniq -c | sed -r 's/^[[:space:]]+//'


