#!/bin/sh

# Copyright: 2014 François Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# We assume that there is a ".my.cnf" file in the home of root.
echo "SHOW GLOBAL STATUS LIKE 'Threads%';" | mysql \
    | tr '[:upper:]' '[:lower:]'                   \
    | sed -nr -e 's/[[:space:]]+/ /g'              \
              -e 's/\t/ /g'                        \
              -e 's/([^[:space:]]*) +/\1=/g'       \
              -e '/thread/p'


