#!/bin/sh

# Copyright: 2014 Francois Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"


if ! which ceph >/dev/null 2>&1
then
    echo "No ceph command found. The package ceph is probably not installed."
    exit 1
fi

if ! which jq >/dev/null 2>&1
then
    echo "No jq command found and it's necessary to check the ceph status."
    exit 1
fi

if json=$(timeout --kill-after=5s 10s ceph --format=json status 2>&1)
then
  printf '%s' "$json" | jq -r '.["health"] | .["overall_status"]'
  exit 0
else
  echo "The command [ceph status] has failed."
  exit 1
fi


