#!/bin/sh

# Copyright: 2013 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

#set -x
SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# The return values of a plugin.
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

OPTIONS_LIST="timeout:,host:,ftp-user:,ftp-password:,file:"

if ! TEMP=$(getopt -o "" -l "$OPTIONS_LIST" -n "$SCRIPT_NAME" -- "$@"); then
    echo "Syntax error with $SCRIPT_NAME command."
    exit $UNKNOWN
fi

eval set -- "$TEMP"
unset TEMP

while true; do

    case "$1" in

        --timeout)
            timeout="$2"
            shift 2
        ;;

        --host)
            host="$2"
            shift 2
        ;;

        --ftp-user)
            ftp_user="$2"
            shift 2
        ;;

        --ftp-password)
            ftp_password="$2"
            shift 2
        ;;

        --file)
            file="$2"
            shift 2
        ;;

        --)
            shift 1
            break
        ;;

    esac
done




if [ -z "$timeout" ] || [ -z "$host" ] || [ -z "$ftp_user" ] \
   || [ -z "$ftp_password" ] || [ -z "$file" ]
then
    echo "$SCRIPT_NAME: at least one option is empty."
    exit "$CRITICAL"
fi

if timeout --signal=KILL "$timeout" ftp-upload --host="$host" \
    --user="$ftp_user" --password="$ftp_password" "$file" > /dev/null 2>&1
then
    echo "FTP upload OK (upload of the local file $file)."
    exit "$OK"
else
    echo "FTP upload CRITICAL (attempt to upload the local file $file)."
    exit "$CRITICAL"
fi


