#!/bin/sh

# Copyright: 2013 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

#set -x
SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}

. "$SCRIPT_DIRECTORY/share/check_snmp_header"


# The oid for RFC1213-MIB::sysDescr.0.
OID='.1.3.6.1.2.1.1.1.0'

# Getting of the uname output.
if output=$(snmpget -OvQ -r "$retry" -t "$timeout" $AUTH_OPTIONS "$host" "$OID" 2>&1); then

    # The "snmpget" command has succeeded.
    output=$(echo "$output" | tr -d '"')
    output=$(echo $output) # strip

    # It's the first check.
    if [ -z "$perfdata" ]; then
        echo "First check OK: uname is $output. | $output"
        exit "$OK"
    fi

    # It isn't the first check.
    perfdata=$(echo $perfdata) # strip
    if [ "$output" = "$perfdata" ]; then
        echo "No change OK: uname is $output. | $output"
        exit "$OK"
    else
        echo "Change WARNING: uname is $output, but was $perfdata. | $output"
        exit "$WARNING"
    fi

else

    # The "snmpget" command hasn't succeeded.
    echo "$output | $perfdata"
    exit "$UNKNOWN"

fi



