#!/bin/sh

SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}
SPECIFIC_SHORT_OPTIONS='p:'
SPECIFIC_LONG_OPTIONS='processes:'
SPECIFIC_SYNOPSIS='--processes "process1 process2..."'

GET_SPECIFIC_OPTIONS () {

    case "$1" in

        --processes|-p)
            processes="$2"
            return 2
        ;;

    esac

    return 0
}

. "$SCRIPT_DIRECTORY/share/snmp.sh"

# The oid 'NET-SNMP-EXTEND-MIB::nsExtendOutputFull."get_processes"' in text format.
oid='.1.3.6.1.4.1.8072.1.3.2.3.1.2.13.103.101.116.95.112.114.111.99.101.115.115.101.115'

output=$(snmpget $SNMP_CMD_OPTIONS -OvQ "$HOSTNAME" "$oid" 2>&1)

# Remove leading double quotes.
output="${output#\"}"
output="${output%\"}"

if printf '%s' "$output" | head -n1 | grep -Eq '^[0-9]+ [A-Z] [^[:space:]]+$'
then
    not_present=''
    for process in $processes
    do
        if ! printf '%s' "$output" | grep -q " ${process}\$"
        then
          not_present="$not_present $process"
        fi
    done

    if [ -z "$not_present" ]
    then
        printf 'OK, the following processes are present: %s.\n' "$processes"
        exit "$CODE_OK"
    else
        printf 'WARNING, the following processes are not present:%s.\n' "$not_present"
        exit "$CODE_WARNING"
    fi
else
    printf 'Unexpected output: %s\n' "$output"
    exit "$CODE_UNKNOWN"
fi


