#!/bin/sh

SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}
SPECIFIC_SHORT_OPTIONS=''
SPECIFIC_LONG_OPTIONS=''
SPECIFIC_SYNOPSIS=''

GET_SPECIFIC_OPTIONS () {
    return 0
}

. "$SCRIPT_DIRECTORY/share/snmp.sh"

# The oid 'NET-SNMP-EXTEND-MIB::nsExtendOutputFull."get_mongodb_rs_status"' in text format.
oid='.1.3.6.1.4.1.8072.1.3.2.3.1.2.21.103.101.116.95.109.111.110.103.111.100.98.95.114.115.95.115.116.97.116.117.115'

# Getting of the mongodb rs status.
output=$(snmpget $SNMP_CMD_OPTIONS -OvQ "$HOSTNAME" "$oid" 2>&1)

# Remove leading double quotes.
output="${output#\"}"
output="${output%\"}"

if [ "$output" = '1' ]
then
    echo "The MongoDB replica set is OK, all members are OK."
    exit "$CODE_OK"
else
    # There is something wrong.
    printf 'Something is wrong with the MongoDB replica set.\n'
    exit "$CODE_CRITICAL"
fi


