#!/bin/sh

# Copyright: 2013 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

#set -x
SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}

. "$SCRIPT_DIRECTORY/share/check_snmp_header"

OID='NET-SNMP-EXTEND-MIB::nsExtendOutputFull."get_puppet_run"'

# The perfdata follow this pattern :
#   run1=<timestamp>;<changed>;<failed> run2=<timestamp>;<changed>;<failed> run3=<timestamp>;<changed>;<failed>

# Getting of the puppet information.
if output=$(snmpget -OvQ -r "$retry" -t "$timeout" $AUTH_OPTIONS "$host" $OID 2>&1) \
    && echo "$output" | grep -qE '^[0-9]*;[0-9]*;[0-9]*'
then

    "$SCRIPT_DIRECTORY/check_snmp_puppet_run_core" "$output" "$puppet_history" "$perfdata" "$warning" "$critical"
    exit "$?"

else

    # The "snmpget" command hasn't succeeded.
    echo "$output"
    exit "$UNKNOWN"

fi



