#!/bin/sh

# Copyright: 2013 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

#set -x
SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}

. "$SCRIPT_DIRECTORY/share/check_snmp_header"


# Getting of the snmp status.
if output=$(snmpstatus -t "$timeout" -r "$retry" $AUTH_OPTIONS "$host" 2>&1)
then

    # The "snmpstatus" command has succeeded.
    echo "SNMP status OK."
    exit "$OK"

else

    # The "snmpstatus" command hasn't succeeded.
    echo "SNMP status CRITICAL. $output"
    exit "$CRITICAL"

fi



