#!/bin/sh

# Copyright: 2013 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

#set -x
SCRIPT_NAME=${0##*/}
SCRIPT_DIRECTORY=${0%/*}

. "$SCRIPT_DIRECTORY/share/check_snmp_header"

# The oid which will run the "snmp_extend_get_raid_status" script on the node.
OID='NET-SNMP-EXTEND-MIB::nsExtendOutputFull."get_raid_status"'

# Getting of the raid status.
# We must check the output because with the NET-SNMP-EXTEND-MIB, snmpget can
# return 0 even if the OID doesn't exist.
if output=$(snmpget -OvQ -r "$retry" -t "$timeout" $AUTH_OPTIONS "$host" "$OID" 2>&1) \
    && echo "$output" | grep -qi "^RAID"
then

    # The "snmpget" command has succeeded and the ouput has the good format.
    echo "$output"

    if echo "$output" | grep -qi "^RAID OK"; then
        exit "$OK"
    else
        exit "$WARNING"
    fi

else

    # The "snmpget" command hasn't succeeded.
    echo "$output"
    exit "$UNKNOWN"

fi



