#!/bin/sh

# Copyright: 2014 Francois Lafont <francois.lafont@ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
SCRIPT_NAME=${0##*/}

print_help () {
    synopsis="[--check-icmp <path>] [--attempts <integer>]"
    synopsis="$synopsis [--pause <number-of-seconds>] -- [<check_icmp options>...]"
    cat <<EOF
The syntax is:
    $SCRIPT_NAME --help
    $SCRIPT_NAME $synopsis
EOF
}

# The return values of a nagios plugin.
CODE_OK=0
CODE_WARNING=1
CODE_CRITICAL=2
CODE_UNKNOWN=3

long_options='help,check-icmp:,attempts:,pause:'
if ! TEMP=$(getopt -o 'h' -l "$long_options" -n "$SCRIPT_NAME" -- "$@")
then
    printf "Syntax error with $SCRIPT_NAME command.\n" >&2
    exit "$CODE_UNKNOWN"
fi

eval set -- "$TEMP"
unset TEMP

# Default values.
CHECK_ICMP='/usr/lib/nagios/plugins/check_icmp'
ATTEMPTS=1
PAUSE=1

while true
do
    case "$1" in

        --check-icmp)
            CHECK_ICMP="$2"
            shift 2
        ;;


        --attempts)
            ATTEMPTS="$2"
            shift 2
        ;;

        --pause)
            PAUSE="$2"
            shift 2
        ;;

        --help|-h)
            print_help
            exit "$CODE_OK"
        ;;

        --)
            shift 1
            break
        ;;

    esac
done

c=0

while true
do
    output=$("$CHECK_ICMP" "$@"); rt=$?
    c=$((c+1))

    if [ "$rt" = "$CODE_OK" ] || [ "$rt" = "$CODE_WARNING" ] || \
       [ "$c" = "$ATTEMPTS" ]
    then
        echo "$output"
        exit "$rt"
    else
        sleep "$PAUSE"
    fi
done


